set foreign_key_checks = 0;
truncate table user;
truncate table carousel_like;
truncate table media;
truncate table accounting;
truncate table type_service;
truncate table type_produit;
truncate table category_accounting;
truncate table rdv;
truncate table produit;